live_config_reload = true

[window]
decorations = "none"
opacity = 1
dynamic_title = false
startup_mode = "Maximized"

  [window.padding]
  x = 5
  y = 5

[scrolling]
history = 10_000
multiplier = 3

[selection]
save_to_clipboard = true

[font]
size = 14

  [font.normal]
  family = "JetBrainsMono Nerd Font"
  style = "Light"

  [font.bold]
  family = "JetBrainsMono Nerd Font"
  style = "Bold"

  [font.italic]
  family = "JetBrainsMono Nerd Font"
  style = "Italic"

  [font.bold_italic]
  family = "JetBrainsMono Nerd Font"
  style = "Bold Italic"

  [font.offset]
  x = 0
  y = 0

[colors.primary]
background = "0x24283b"
foreground = "0xc0caf5"

[colors.normal]
black = "0x1D202F"
red = "0xf7768e"
green = "0x9ece6a"
yellow = "0xe0af68"
blue = "0x7aa2f7"
magenta = "0xbb9af7"
cyan = "0x7dcfff"
white = "0xa9b1d6"

[colors.bright]
black = "0x414868"
red = "0xf7768e"
green = "0x9ece6a"
yellow = "0xe0af68"
blue = "0x7aa2f7"
magenta = "0xbb9af7"
cyan = "0x7dcfff"
white = "0xc0caf5"

[[colors.indexed_colors]]
index = 16
color = "0xff9e64"

[[colors.indexed_colors]]
index = 17
color = "0xdb4b4b"
